import { copyFile, mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import type { LibraryRecord } from "../../shared/library-types";
import type { ExportAssetContext, ExportRunSummary } from "../../shared/export-types";
import { APP_NAME } from "../../shared/app-metadata";
import { safeFileName, toCsv } from "./game-audio-manifest-service";

export interface SoundPackExportOptions {
  includeAudioFiles: boolean;
  includeAbsolutePaths: boolean;
  includeCollections: boolean;
  includeRights: boolean;
}

export interface SoundPackExportResult {
  outputPath: string;
  files: string[];
  summary: ExportRunSummary;
}

export class SoundPackExportService {
  async exportFolder(
    outputPath: string,
    library: LibraryRecord,
    contexts: ExportAssetContext[],
    options: SoundPackExportOptions,
  ): Promise<SoundPackExportResult> {
    await mkdir(outputPath, { recursive: false });
    const files: string[] = [];
    const summary: ExportRunSummary = {
      requested: contexts.length,
      exported: 0,
      skipped: 0,
      failed: 0,
      warnings: [],
    };

    const manifestPath = join(outputPath, "manifest.json");
    const readmePath = join(outputPath, "README.md");
    const metadataPath = join(outputPath, "metadata");
    await mkdir(metadataPath, { recursive: true });

    if (options.includeAudioFiles) {
      for (const context of contexts) {
        const sourcePath = getAssetFilePath(context);
        if (!sourcePath) {
          summary.skipped += 1;
          summary.warnings.push(`Missing file skipped: ${context.asset.fileName}`);
          continue;
        }
        const targetPath = join(outputPath, "audio", context.relativePath);
        try {
          await mkdir(dirname(targetPath), { recursive: true });
          await copyFile(sourcePath, targetPath);
          files.push(targetPath);
          summary.exported += 1;
        } catch (error) {
          summary.failed += 1;
          summary.warnings.push(
            `Copy failed (${context.asset.fileName}): ${error instanceof Error ? error.message : String(error)}`,
          );
        }
      }
    }

    const manifest = {
      app: APP_NAME,
      soundPackVersion: 1,
      createdAt: new Date().toISOString(),
      libraryName: library.name,
      assetCount: contexts.length,
      includesAudioFiles: options.includeAudioFiles,
      assets: contexts.map((context) => ({
        id: context.asset.id,
        engineKey: context.engineKey,
        fileName: context.asset.fileName,
        exportedFileName: context.outputFileName,
        relativePath: context.relativePath.replace(/\\/g, "/"),
        category: context.category,
        tags: context.asset.tags.map((tag) => tag.name),
        collections: options.includeCollections ? context.asset.collections.map((collection) => collection.name) : undefined,
        sourcePath: options.includeAbsolutePaths ? getAssetFilePath(context) : undefined,
        license: options.includeRights
          ? {
              name: context.rights.licenseName,
              author: context.rights.author,
              attribution: context.rights.attributionText,
              sourceUrl: context.rights.sourceUrl,
            }
          : undefined,
      })),
    };

    await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
    await writeFile(readmePath, createReadme(library, contexts, options), "utf8");
    await writeFile(join(metadataPath, "assets.csv"), createAssetsCsv(contexts, options), "utf8");
    await writeFile(join(metadataPath, "tags.csv"), createTagsCsv(contexts), "utf8");
    await writeFile(join(metadataPath, "collections.csv"), createCollectionsCsv(contexts), "utf8");
    files.push(manifestPath, readmePath, join(metadataPath, "assets.csv"), join(metadataPath, "tags.csv"), join(metadataPath, "collections.csv"));

    if (!options.includeAudioFiles) {
      summary.exported = contexts.length;
    }

    return { outputPath, files, summary };
  }
}

function createReadme(
  library: LibraryRecord,
  contexts: ExportAssetContext[],
  options: SoundPackExportOptions,
): string {
  const creditLines = contexts
    .filter((context) => context.rights.creditRequired === "yes" || context.rights.attributionText)
    .map((context) => `* ${context.asset.fileName}: ${context.rights.attributionText || "TODO: attribution required"}`);
  return `# ${library.name} Sound Pack

Generated by ${APP_NAME}.

## Contents

* Assets: ${contexts.length}
* Audio files included: ${options.includeAudioFiles ? "yes" : "no"}
* Paths: ${options.includeAbsolutePaths ? "relative and absolute" : "relative only"}

## License And Credits

This file records user-entered rights metadata only. It is not legal advice and does not infer licenses.

${creditLines.length ? creditLines.join("\n") : "* TODO: Review source, license, and attribution metadata before shipping."}

## MonoGame Note

MonoGame importer and processor support varies by format and platform. Review WAV, MP3, and OGG handling in your target Content Pipeline.
`;
}

function createAssetsCsv(contexts: ExportAssetContext[], options: SoundPackExportOptions): string {
  return toCsv(
    contexts.map((context) => ({
      id: context.asset.id,
      engineKey: context.engineKey,
      fileName: context.asset.fileName,
      exportedFileName: context.outputFileName,
      relativePath: context.relativePath,
      category: context.category,
      tags: context.asset.tags.map((tag) => tag.name).join(";"),
      collections: context.asset.collections.map((collection) => collection.name).join(";"),
      durationMs: context.asset.audioAnalysis?.durationMs ?? "",
      sourcePath: options.includeAbsolutePaths ? getAssetFilePath(context) : "",
      licenseName: options.includeRights ? context.rights.licenseName : "",
      author: options.includeRights ? context.rights.author : "",
      attributionText: options.includeRights ? context.rights.attributionText : "",
    })),
  );
}

function createTagsCsv(contexts: ExportAssetContext[]): string {
  const counts = new Map<string, number>();
  for (const context of contexts) {
    for (const tag of context.asset.tags) {
      counts.set(tag.name, (counts.get(tag.name) ?? 0) + 1);
    }
  }
  return toCsv(Array.from(counts, ([name, assetCount]) => ({ name, assetCount })));
}

function createCollectionsCsv(contexts: ExportAssetContext[]): string {
  const counts = new Map<string, number>();
  for (const context of contexts) {
    for (const collection of context.asset.collections) {
      counts.set(collection.name, (counts.get(collection.name) ?? 0) + 1);
    }
  }
  return toCsv(Array.from(counts, ([name, assetCount]) => ({ name, assetCount })));
}

function getAssetFilePath(context: ExportAssetContext): string | null {
  const asset = context.asset;
  if (asset.fileMissing) {
    return null;
  }
  return asset.importMode === "copy" && asset.storedPath ? asset.storedPath : asset.originalPath;
}

export function safeSoundPackFolderName(input: string): string {
  return safeFileName(input || "exported-sound-pack").replace(/\.[^.]+$/, "") || "exported-sound-pack";
}
