export type AppErrorCode =
  | "LIBRARY_CREATE_FAILED"
  | "LIBRARY_OPEN_FAILED"
  | "IMPORT_FAILED"
  | "IMPORT_UNSUPPORTED_FILE"
  | "IMPORT_DUPLICATE_FILE"
  | "IMPORT_FILE_MISSING"
  | "IMPORT_PERMISSION_DENIED"
  | "IMPORT_COPY_FAILED"
  | "IMPORT_HASH_FAILED"
  | "IMPORT_CORRUPTED_FILE"
  | "ASSET_NOT_FOUND"
  | "ANALYSIS_FAILED"
  | "ANALYSIS_METADATA_FAILED"
  | "TAG_APPLY_FAILED"
  | "COLLECTION_UPDATE_FAILED"
  | "TRASH_FAILED"
  | "RESTORE_FAILED"
  | "DELETE_PERMANENT_FAILED"
  | "PLAYBACK_UNSUPPORTED"
  | "PLAYBACK_FILE_MISSING"
  | "LIBRARY_DIAGNOSTICS_FAILED"
  | "FILE_MISSING"
  | "RELINK_FAILED"
  | "DUPLICATE_MERGE_FAILED"
  | "BACKUP_FAILED"
  | "METADATA_EXPORT_FAILED"
  | "TAG_RENAME_FAILED"
  | "TAG_MERGE_FAILED"
  | "COLLECTION_RENAME_FAILED"
  | "IMPORT_SOURCE_SCAN_FAILED"
  | "SIDECAR_EXPORT_FAILED"
  | "EXPORT_PREVIEW_FAILED"
  | "EXPORT_RUN_FAILED"
  | "EXPORT_CANCELLED"
  | "EXPORT_NO_ASSETS"
  | "EXPORT_TARGET_EXISTS"
  | "EXPORT_MISSING_FILES"
  | "EXPORT_DUPLICATE_KEYS"
  | "EXPORT_WRITE_FAILED"
  | "EXPORT_PERMISSION_DENIED"
  | "EXPORT_INVALID_PRESET"
  | "BACKUP_TARGET_EXISTS"
  | "BACKUP_PERMISSION_DENIED"
  | "BACKUP_COPY_FAILED"
  | "RIGHTS_UPDATE_FAILED"
  | "PRESET_SAVE_FAILED"
  | "PRESET_DELETE_FAILED"
  | "CODEX_INSTRUCTION_PREVIEW_FAILED"
  | "MANIFEST_PREVIEW_FAILED"
  | "SOUND_WORKFLOW_LOAD_FAILED"
  | "SOUND_WORKFLOW_UPDATE_FAILED"
  | "CANDIDATE_REVIEW_UPDATE_FAILED"
  | "STYLE_GUIDE_LOAD_FAILED"
  | "STYLE_GUIDE_UPDATE_FAILED"
  | "CHECKLIST_LOAD_FAILED"
  | "CHECKLIST_UPDATE_FAILED"
  | "SOUND_REQUEST_PREVIEW_FAILED"
  | "SOUND_REQUEST_EXPORT_FAILED"
  | "SNAPSHOT_CREATE_FAILED"
  | "SNAPSHOT_LOAD_FAILED"
  | "SNAPSHOT_DELETE_FAILED"
  | "SNAPSHOT_FREEZE_FAILED"
  | "SNAPSHOT_COMPARE_FAILED"
  | "SNAPSHOT_ROLLBACK_PREVIEW_FAILED"
  | "SNAPSHOT_ROLLBACK_APPLY_FAILED"
  | "CHANGELOG_EXPORT_FAILED"
  | "BASELINE_SET_FAILED"
  | "FEATURE_ANALYSIS_FAILED"
  | "FEATURE_RERUN_FAILED"
  | "SIMILARITY_SEARCH_FAILED"
  | "SIMILARITY_CACHE_FAILED"
  | "LOOP_ANALYSIS_FAILED"
  | "UNKNOWN_ERROR";

export interface LocalizedAppError {
  code: AppErrorCode;
  message?: string;
  params?: Record<string, string | number>;
}

export interface AppErrorResponse {
  ok: false;
  error: {
    code: AppErrorCode;
    message: string;
    details?: string;
    recoverable?: boolean;
  };
}
